#!/bin/bash

export TF_VAR_user_ocid=ocid1.user.oc1..aaaaaaaapjhoepwrsfnwxsk6fztrogtmz2mlqp6nz6jgkbdt2xv4t5xnn5hq
export TF_VAR_compartment_ocid=ocid1.compartment.oc1..aaaaaaaakyxvmnotwlokb6rcvhr4bee2kw4ez2hxvlxhk2rrmnobbp24vksa
export TF_VAR_deployment_auuid=deploy1
export TF_VAR_deployment_short_id=123
export TF_VAR_fingerprint=c6:2b:d6:c7:54:81:23:c3:7c:81:f9:41:e6:bc:8e:1a
export TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaa74wp4expt3ltekxhzy5wa4nymgtpbcn6dgwogqprkgxq57uqfslq
export TF_VAR_user_email=derek.oneill@oracle.com
export TF_VAR_user_name=derekoneil


#default_security_list_id = "${oci_core_security_list.ExampleVCNSecList.id}"
