load data 
infile 'credit_scoring_100k.csv' "str '\n'"
append
into table CREDIT_SCORING_100K
fields terminated by ','
OPTIONALLY ENCLOSED BY '"' AND '"'
trailing nullcols
           ( CUSTOMER_ID,
             AGE,
             INCOME,
             MARITAL_STATUS CHAR(26),
             NUMBER_OF_LIABLES,
             WEALTH CHAR(4000),
             EDUCATION_LEVEL CHAR(26),
             TENURE,
             LOAN_TYPE CHAR(26),
             LOAN_AMOUNT,
             LOAN_LENGTH,
             GENDER CHAR(26),
             REGION CHAR(26),
             CURRENT_ADDRESS_DURATION,
             RESIDENTAL_STATUS CHAR(26),
             NUMBER_OF_PRIOR_LOANS,
             NUMBER_OF_CURRENT_ACCOUNTS,
             NUMBER_OF_SAVING_ACCOUNTS,
             OCCUPATION CHAR(26),
             HAS_CHECKING_ACCOUNT CHAR(26),
             CREDIT_HISTORY CHAR(26),
             PRESENT_EMPLOYMENT_SINCE CHAR(26),
             FIXED_INCOME_RATE,
             DEBTOR_GUARANTORS CHAR(26),
             HAS_OWN_PHONE_NO CHAR(26),
             HAS_SAME_PHONE_NO_SINCE,
             IS_FOREIGN_WORKER CHAR(26),
             NUMBER_OF_OPEN_ACCOUNTS,
             NUMBER_OF_CLOSED_ACCOUNTS,
             NUMBER_OF_INACTIVE_ACCOUNTS,
             NUMBER_OF_INQUIRIES,
             HIGHEST_CREDIT_CARD_LIMIT,
             CREDIT_CARD_UTILIZATION_RATE,
             DELINQUENCY_STATUS CHAR(26),
             NEW_BANKRUPTCY CHAR(26),
             NUMBER_OF_COLLECTIONS,
             MAX_CC_SPENT_AMOUNT,
             MAX_CC_SPENT_AMOUNT_PREV,
             HAS_COLLATERAL CHAR(26),
             FAMILY_SIZE,
             CITY_SIZE CHAR(26),
             FATHERS_JOB CHAR(26),
             MOTHERS_JOB CHAR(26),
             MOST_SPENDING_TYPE CHAR(26),
             SECOND_MOST_SPENDING_TYPE CHAR(26),
             THIRD_MOST_SPENDING_TYPE CHAR(26),
             SCHOOL_FRIENDS_PERCENTAGE,
             JOB_FRIENDS_PERCENTAGE,
             NUMBER_OF_PROTESTOR_LIKES,
             NO_OF_PROTESTOR_COMMENTS,
             NO_OF_LINKEDIN_CONTACTS,
             AVERAGE_JOB_CHANGING_PERIOD,
             NO_OF_DEBTORS_ON_FB,
             NO_OF_RECRUITERS_ON_LINKEDIN,
             NO_OF_TOTAL_ENDORSEMENTS,
             NO_OF_FOLLOWERS_ON_TWITTER,
             MODE_JOB_OF_CONTACTS CHAR(26),
             AVERAGE_NO_OF_RETWEETS,
             FACEBOOK_INFLUENCE_SCORE,
             PERCENTAGE_PHD_ON_LINKEDIN,
             PERCENTAGE_MASTERS,
             PERCENTAGE_UG,
             PERCENTAGE_HIGH_SCHOOL,
             PERCENTAGE_OTHER,
             IS_POSTED_STH_WITHIN_A_MONTH CHAR(26),
             MOST_POPULAR_POST_CATEGORY CHAR(26),
             INTEREST_RATE,
             EARNINGS,
             UNEMPLOYMENT_INDEX,
             PRODUCTION_INDEX,
             HOUSING_INDEX,
             CONSUMER_CONFIDENCE_INDEX,
             INFLATION_RATE,
             CUSTOMER_VALUE_SEGMENT CHAR(26),
             CUSTOMER_DMG_SEGMENT CHAR(26),
             CUSTOMER_LIFETIME_VALUE,
             CHURN_RATE_OF_CC1,
             CHURN_RATE_OF_CC2,
             CHURN_RATE_OF_CCN,
             CHURN_RATE_OF_ACCOUNT_NO1,
             CHURN_RATE__OF_ACCOUNT_NO2,
             CHURN_RATE_OF_ACCOUNT_NON,
             HEALTH_SCORE,
             CUSTOMER_DEPTH,
             LIFECYCLE_STAGE,
             CREDIT_SCORE_BIN CHAR(100)
           )
