#!/bin/bash
echo '########## yum update all ###############'
touch /root/starting_run
yum update -y

echo '################### webserver userdata begins #####################'
yum install -y httpd
systemctl enable  httpd.service
systemctl start  httpd.service

echo '########## basic webserver ##############'
yum install -y httpd
systemctl enable  httpd.service
systemctl start  httpd.service
echo '<html><head></head><body><pre><code>' > /var/www/html/index.html
hostname >> /var/www/html/index.html
echo '' >> /var/www/html/index.html
cat /etc/os-release >> /var/www/html/index.html
echo '</code></pre></body></html>' >> /var/www/html/index.html
firewall-offline-cmd --add-service=http
systemctl enable  firewalld
systemctl restart  firewalld

touch /root/run_complete